name: getx_clean_template_vip
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  dio: ^5.2.1
  get_storage: ^2.1.1
  url_launcher: ^6.0.9
  device_info_plus: ^9.0.2
  intl: ^0.17.0
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.2
  equatable: ^2.0.3
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  connectivity_plus: ^4.0.1
  permission_handler: ^10.0.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter



  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/texts/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/PoppinsBold.ttf
          weight: 700
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
